
image: python:3-alpine

stages:
  - build

wheel:
  stage: build
  script:
    - python setup.py bdist_wheel
    - cat $PYPIRC > /tmp/.pypirc
    - pip install twine
    - python -m twine upload --repository gitlab dist/*.whl --config-file /tmp/.pypirc
  only:
    - tags
  artifacts:
    paths:
    - dist/
    expire_in: 1 week
